### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by jzheng2017** [czyzby/noise4j#3]
Hi,

Could you point me to the package or class where the seeding is made possible? I am very curious how it is done. 

Thanks

**Comment by czyzby** [comment]
It's been a while since I've touched this project, but I believe you're looking for there:
- [Generators util class](https://github.com/czyzby/noise4j/blob/master/src/com/github/czyzby/noise4j/map/generator/util/Generators.java) allows you to set a `Random` instance used by the generators globally. These can be seeded for reproducible results.
- [NoiseGenerator](https://github.com/czyzby/noise4j/blob/master/src/com/github/czyzby/noise4j/map/generator/noise/NoiseGenerator.java#L163-L166) uses a noise function based on a pre-defined seed.
